spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/library
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_HOST:http://localhost:8761/eureka}
    enabled: true
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 30
    instance-id: book-service